name: 'Drop MySQL Database'
description: ''
inputs:
  database-name:
    description: 'Name of database to be dropped'
    required: true
    default: ''
  host:
    description: 'Database server host'
    required: true
    default: ''
  user:
    description: 'Database server username'
    required: true
    default: ''
  password:
    description: 'Database server password'
    required: true
    default: ''  
outputs:
    status:
    description: 'Action result'
runs:
  using: 'node12'
  main: 'index.js'