name: 'Drop MySQL Database'
description: ''
inputs:
  database-name:
    description: 'Name of database to be dropped'
    required: true
    default: 'temp'
  host:
    description: 'Database server host'
    required: true
    default: 'localhost'
  user:
    description: 'Database server username'
    required: true
    default: 'root'
  password:
    description: 'Database server password'
    required: true
    default: 'root'
outputs:
  status:
    description: '0 if response code returned within timeout, otherwise 1'
runs:
  using: 'node12'
  main: 'index.js'
